### ISSUE TITLE
Array To String conversion

### ISSUE THREAD

**Issue by joshharington** [econea/nusoap#7]
I am getting an error of `Array to string conversion in lib/nusoap.php on line 1703`

**Comment by f3l1x** [comment]
Thanks. I will take a look.

**Comment by f3l1x** [comment]
@joshharington Could you please provide more info? Which PHP version at first? :-)

**Comment by yashari01** [comment]
Hello,i'm getting also error of Array to string conversion in lib/nusoap.php  but on line 7481
i'm using php 7.1

**Comment by f3l1x** [comment]
@joshharington @yashari01 Could you please send a PR?

**Comment by raphaelrosello** [comment]
I'm also getting the same error on client call passing a multidimensional array. Sample below

```
$response = $client->call('Logon', [
          'Username' => 'user',
          'Password' => 'password'
    ]);
```

This is the format of the XML I'm suppose to pass.

```
<Logon>
	<logonRequest>
		<Username>user</Username>
		<Password>password</Password>
	</logonRequest>
</Logon>
```

**Comment by Worka** [comment]
Hello! Too

**Array to string conversion**

/vendor/econea/nusoap/src/nusoap.php:7605

var_dump $k & $v

```
/vendor/econea/nusoap/src/nusoap.php:7603:string 'faultcode' (length=9)
/vendor/econea/nusoap/src/nusoap.php:7604:string 'soapenv:Server' (length=14)
/vendor/econea/nusoap/src/nusoap.php:7603:string 'faultstring' (length=11)
/vendor/econea/nusoap/src/nusoap.php:7604:string 'bla bla bla' (length=81)
/vendor/econea/nusoap/src/nusoap.php:7603:string 'detail' (length=6)
/vendor/econea/nusoap/src/nusoap.php:7604:
array (size=1)
  'Exception' => string '' (length=0)
```

**Comment by f3l1x** [comment]
Could you guys send a PR to master branch?

**Comment by f3l1x** [comment]
ping @Worka @raphaelrosello @joshharington

**Comment by Worka** [comment]
I can`t install

> Could not find a matching version of package ^0.9.6. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).

**Comment by f3l1x** [comment]
Try 

```json
{
	"require": { "econea/nusoap: ^0.9.6" },
	"prefer-stable": true,
	"minimum-stability": "dev",
}

**Comment by Worka** [comment]
Still could not switch to ^ 0.9.6
Switched to the dev-master
Looked at the change. Yes, the reason for the mistake is eliminated. Everything works perfectly.

**Comment by f3l1x** [comment]
Thanks for testing it. @Worka

**Comment by f3l1x** [comment]
```
{
"require": {
    "econea/nusoap": "^0.9.6"
},
"minimum-stability": "dev",
"prefer-stable": true
}
```

I've fixed it now. Could you test new version?

**Comment by Worka** [comment]
I was able to switch now. It works correctly, but how do I get this build now with the composer's "minimum-stability: stable" settings?

**Comment by f3l1x** [comment]
As soon as I tag it, it will be working. There's a `prefer-stable` option for that. It prefer tags over dev-<brange> builds.

**Comment by f3l1x** [comment]
https://github.com/econea/nusoap/releases/tag/v0.9.6

**Comment by RYRDU** [comment]
I am getting an error of `Array to string conversion in lib/nusoap.php on line 3203`

**Comment by SergioWiesner** [comment]
Array to string conversion

i have the same error, and not is fixed. 

i want make a pull request with the solution for fixed quickly.


this solution is perfect @ezehurt  i like -> 
 if (is_array($v)) {
                        $this->debug("$k = " . json_encode($v));
                    } else {
                        $this->debug("$k = $v<br>");
                    }

**Comment by dbebawy** [comment]
@f3l1x, Can you release a new version 0.9.7 with this fix? The current release 0.9.6 doesn't contain the fix.

**Comment by f3l1x** [comment]
Hi @dbebawy. Released.

https://github.com/econea/nusoap/releases/tag/v0.9.7

**Comment by dbebawy** [comment]
Worked like a charm. Thank you!

**Comment by paulmbaka** [comment]
@f3l1x, could please support with [17-Jun-2020 13:49:05 UTC] PHP Notice:  Array to string conversion in .......lib\nusoap.php on line 6130
